### ISSUE TITLE
alias 'gcs' doesn't work

### ISSUE THREAD

**Issue by kimagedon** [YanWenKun/sd-webui-docker-base#1]
running into an alias problem:
2024-03-01 01:52:32 /home/scripts/download.sh: line 12: gcs: command not found

Docker versions: 4.28.0, 4.17.0 (Win11)

tried to change download.sh file. now it says:
chmod: changing permissions of '/home/scripts/download.sh': Operation not permitted

any solutions?

**Comment by YanWenKun** [comment]
Sorry for that!
It was a stupid mistake 😵, being fixed right away....
