### ISSUE TITLE
下载完了32G 结果没有运行成功 各种报错 有人运行成功过吗

### ISSUE THREAD

**Issue by sufeng** [YanWenKun/sd-webui-docker-base#2]

**Comment by YanWenKun** [comment]
嗨呀，这镜像许久未更新了，我也许久没用过 webui 了，我估摸着应该是 Python 依赖项对不上版本了

**Comment by YanWenKun** [comment]
看了下好像也没啥大变动，就多了几个依赖项，加进来跑一下构建看看

**Comment by sufeng** [comment]
设计思想还是不错的 有空帮忙修复一下 可以跑起来就OK

**Comment by sufeng** [comment]
![image](https://github.com/user-attachments/assets/206d57d2-48af-43f5-976d-1bc5cdbefe9a)
这里的下载保存路径 是不是有问题？

**Comment by YanWenKun** [comment]
> 这里的下载保存路径 是不是有问题？

对，以前aria2能用out=绝对路径，现在不行了，估计是什么安全考量吧，反正刚改了一下

能跑，我简单拿SD 1.5模型跑了张文生图，正常。更多的没测了，缺啥补啥吧

这个镜像里的东西都是SD 1.5时代的，也不好大变动了。新一些的我看forge用的比较多，但我完全没研究，现在基本只玩ComfyUI了

**Comment by sufeng** [comment]
我跑起来测试后发现几个问题：1、少了pip包 controlnet_aux  2、少了模型openai/clip-vit-large-patch14 3、多个模型文件切换时会报错 
![image](https://github.com/user-attachments/assets/864ebc91-fb8f-47cb-a71c-38bc19ed0eeb)

**Comment by YanWenKun** [comment]
> 1、少了pip包 controlnet_aux

解决了

> 2、少了模型openai/clip-vit-large-patch14 

这是插件调用 HF Hub 下载的，跟下载列表里的 clip 文件还不是一个东西，HF Hub 会下载一堆 blob。
与其一个一个找下载链接，有个简单粗暴的办法：

```
# 添加环境变量，使 HuggingFace Hub 使用国内镜像下载
-e HF_ENDPOINT="https://hf-mirror.com"
```

> 3、多个模型文件切换时会报错

看控制台怎么输出的吧。另外默认下载的两个 SD 模型文件，一个 pix2pix，一个 inpainting，都不是“常规”模型，你换其他 SD 1.5 模型试试。
